# Generated by Django 5.2.3 on 2025-06-17 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.TextField(max_length=100)),
                ('Ingredients', models.TextField(max_length=150)),
                ('Instructions', models.TextField(max_length=100)),
                ('Image', models.ImageField(upload_to='media/recipe')),
            ],
        ),
    ]
